### ISSUE TITLE
[todo] main list

### ISSUE THREAD

**Issue by Hongske** [Hongske/subeta-templates#1]
Contains major todo points. Individual points will be divided into separate tickets as they're tackled.

# Pet profiles
- [ ] reset style (see #2) 
- [ ] basic premades
- [ ] more advanced premades

# User profiles
- [ ] reset style
- [ ] basic premades
- [ ] more advanced premades

# Custom CSS
- [ ] upgrades (to extend existing themes)
- [ ] new themes
